[package]
name = "abyss"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29"
crossterm = "0.29"
tokio = { version = "1.48", features = ["full"] }
kube = { version = "2.0", features = ["client", "runtime", "derive", "ws"] }
k8s-openapi = { version = "0.26", features = ["v1_30"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
futures = "0.3"
chrono = "0.4"
jwalk = "0.8"
